
CREATE TABLE "MEMBER"(
 MEMBER_ID        VARCHAR2(20) PRIMARY KEY,
 MEMBER_PW        VARCHAR2(20) NOT NULL,
 MEMBER_NAME      VARCHAR2(20) NOT NULL,
 MEMBER_EMAIL     VARCHAR2(50) NOT NULL,
 MEMBER_PHONE     VARCHAR2(20) NOT NULL,
 MEMBER_AUTH      VARCHAR2(20) NOT NULL
);

CREATE SEQUENCE MEMBER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
CREATE TABLE PRODUCT
(
 PRODUCT_ID          NUMBER PRIMARY KEY,
 MEMBER_ID           VARCHAR2(20) NOT NULL,
 PRODUCT_NAME        VARCHAR2(100) NOT NULL,
 PRODUCT_PRICE       NUMBER NOT NULL,
 REVIEW_NUM          NUMBER NOT NULL,
 PRODUCT_REMAINS     NUMBER NOT NULL,
 PRODUCT_PLACE       VARCHAR2(50) NOT NULL,
 PRODUCT_STATE       VARCHAR2(20) NOT NULL,
 CONSTRAINT FK_PRODUCT_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);   

CREATE SEQUENCE PRODUCT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE PAYMENT
(
 PAYMENT_ID           NUMBER PRIMARY KEY,
 MEMBER_ID            VARCHAR2(20) NOT NULL,
 DELIVERY_ADDRESS     VARCHAR2(50) NOT NULL,
 RECEIVER_NAME        VARCHAR2(20) NOT NULL,
 RECEIVER_PHONE       VARCHAR2(20),
 CONSTRAINT FK_PAYMENT_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

CREATE SEQUENCE PAYMENT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
CREATE TABLE "ORDER"
(
 ORDER_ID                 NUMBER PRIMARY KEY,
 PAYMENT_ID               NUMBER NOT NULL,
 PRODUCT_ID               NUMBER NOT NULL,
 PRODUCT_NAME             VARCHAR2(100) NOT NULL,
 PRODUCT_PRICE            NUMBER NOT NULL,
 PURCHASE_NUM             NUMBER NOT NULL,
 EXPECT_DELIVERY_DATE     TIMESTAMP NOT NULL,
 CONSTRAINT FK_ORDER_PAYMENT_ID FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID),
 CONSTRAINT FK_ORDER_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE SEQUENCE ORDER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE SELLER
(
 MEMBER_ID           VARCHAR2(20) PRIMARY KEY,
 BUSINESS_NAME       VARCHAR2(50) NOT NULL,
 REQUEST_TIME        TIMESTAMP NOT NULL,
 REQUEST_CONTENT     VARCHAR2(100) NOT NULL,
 CONSTRAINT FK_SELLER_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

CREATE TABLE INQUIRY
(
 INQUIRY_ID               NUMBER PRIMARY KEY,
 MEMBER_ID                VARCHAR2(20) NOT NULL,
 PRODUCT_ID               NUMBER NOT NULL,
 INQUIRY_CONTENT          VARCHAR2(500) NOT NULL,
 INQUIRY_DATE_CREATED     TIMESTAMP NOT NULL,
 PARENT_ID                NUMBER,
 CONSTRAINT FK_INQUIRY_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
 CONSTRAINT FK_INQUIRY_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE SEQUENCE INQUIRY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE IMAGE
(
 IMG_ID               NUMBER PRIMARY KEY,
 PRODUCT_ID           NUMBER,
 IMG_PATH             VARCHAR2(200) NOT NULL,
 IMG_REAL_NAME        VARCHAR2(200) NOT NULL,
 IMG_CHANGE_NAME      VARCHAR2(200) NOT NULL,
 IMG_EXTENSION        VARCHAR2(20) NOT NULL,
 IMG_DATE_CREATED     TIMESTAMP NOT NULL,
 CONSTRAINT FK_IMAGE_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE SEQUENCE IMAGE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE REVIEW
(
 REVIEW_ID               NUMBER PRIMARY KEY,
 MEMBER_ID               VARCHAR2(20) NOT NULL,
 PRODUCT_ID              NUMBER NOT NULL,
 REVIEW_CONTENT          VARCHAR2(500) NOT NULL,
 REVIEW_DATE_CREATED     TIMESTAMP NOT NULL,
 REVIEW_STAR             FLOAT NOT NULL,
 REVIEW_LIKE             NUMBER NOT NULL,
 IMG_ID                  NUMBER NULL,
 CONSTRAINT FK_REVIEW_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
 CONSTRAINT FK_REVIEW_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
 CONSTRAINT FK_REVIEW_IMG_ID FOREIGN KEY (IMG_ID) REFERENCES IMAGE(IMG_ID)
);

CREATE SEQUENCE REVIEW_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE APPOINTMENT
(
 APPOINTMENT_ID               NUMBER PRIMARY KEY,
 MEMBER_ID                    VARCHAR2(20) NOT NULL,
 PRODUCT_ID                   NUMBER NOT NULL,
 APPOINTMENT_DATE_CREATED     TIMESTAMP NOT NULL,
 CONSTRAINT FK_APPOINTMENT_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
 CONSTRAINT FK_APPOINTMENT_PRODUCT_ID FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);


CREATE SEQUENCE APPOINTMENT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE BASKET
(
 MEMBER_ID       VARCHAR2(20) NOT NULL,
 PRODUCT_ID      NUMBER NOT NULL,
 PRODUCT_NUM     NUMBER NOT NULL,
 CONSTRAINT FK_BASKET_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
 CONSTRAINT FK_BASKET_PRODUCT_ID FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE COUPON
(
 COUPON_NAME      VARCHAR2(50) ,
 MEMBER_ID        VARCHAR2(20) ,
 VALID_PERIOD     TIMESTAMP NOT NULL,
 DISCOUNT         NUMBER NOT NULL,
 COUPON_NUM       NUMBER NOT NULL,
 CONSTRAINT PK_COUPON PRIMARY KEY(COUPON_NAME, MEMBER_ID),
 CONSTRAINT FK_COUPON_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

CREATE TABLE DELIVERY
(
 DELIVERY_ID          NUMBER PRIMARY KEY,
 MEMBER_ID            VARCHAR2(20) NOT NULL,
 RECEIVER_NAME        VARCHAR2(20) NOT NULL,
 RECEIVER_ADDRESS     VARCHAR2(100) NOT NULL,
 RECEIVER_PHONE       VARCHAR2(20),
 REQUIREMENT          VARCHAR2(100),
 CONSTRAINT FK_DELIVERY_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

CREATE SEQUENCE DELIVERY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE REGULAR_PURCHASE
(
 PAYMENT_ID          NUMBER PRIMARY KEY,
 DELIVERY_INTERVAL     NUMBER NOT NULL,
 CONSTRAINT FK_REGULAR_PAYMENT_ID FOREIGN KEY(PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID)
);


